# MACHINE LEARNING :

- is making the computer learn from studying data and statistics.
- is a step into the direction of artificial intelligence (AI).
- is a program that analyses data and learns to predict the outcome.

###### ML Libraries :
      - Numpy
      - Pandas
      - Matplotlib
      - Seaborn
      - Scipy
      - Sklearn

#### NumPy : Package for MultiDimensional Array
#### Vector(1d)
#### Matrix(2d or 1d)

In [1]:
import numpy as np ### use this in all Algorithm becoz whenever we talk about Data we are going to deal with the numbers, whenever we deal with the number, the library that is used to deal with the numbers is called as NumPy.
                   ### np is alias
                   ### we can write anything in place of np as alias

In [2]:
simple_list = [10,20,30,40]  ### List
np.array(simple_list)        ### Create an 1-D Array using "np.array()" function

array([10, 20, 30, 40])

In [3]:
number_In_Array = np.array([10,20,30,40]) ### create an 1-D array directly using list
number_In_Array

array([10, 20, 30, 40])

In [4]:
number_In_Array = np.array((10,20,30,40)) ### create an 1-D array directly using tuple
number_In_Array

array([10, 20, 30, 40])

In [5]:
np.array([[1, 2, 3, 4], [5, 6, 7, 8]])  ## np.array(([1, 2, 3, 4], [5, 6, 7, 8]))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
list_of_lists = ([1,2,3,4],[5,6,7,8],[9,10,11,12]) ### Tuple - collection of Lists
np.array(list_of_lists)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
arr=np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
list_of_lists = [[1,2,3,4],[5,6,7,8],[9,10,11,12]] ### List - Collection of lists
np.array(list_of_lists)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
simple_list = (10,20,30,40)   ### Tuple
np.array(simple_list)         ### Create an 1-D array using Tuple

array([10, 20, 30, 40])

In [11]:
np.arange(20) ### It's "arange" not "arrange". 
              ### It's start by default from 0 with 1 increment to last with 19 (n-1).Last number always excluded.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
np.arange(5,20) ### It's start from 5 with 1 increment to last with 19 (n-1).Last number always excluded.

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.arange(5,35,6) ### Here 6 is step size.

array([ 5, 11, 17, 23, 29])

#### np.zeros()
#### elements data type is float by default
#### all elements are 0
#### number of zeroes are given as first argument in parathesis

In [14]:
np.zeros(5) ### It's zeros "not zeroes".

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros(5,dtype=int) ### Here DataType is integer

array([0, 0, 0, 0, 0])

In [16]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros((2,5),dtype=int) ### Here (2,5) - 2 rows and 5 columns

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

#### np.ones()
#### elements data type is float by default
#### all elements are 1
#### number of ones are given as first argument in parathesis

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [20]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

#### np.linspace() - equally space b/w them.
#### Number of samples to generate by Default is 50. Must be non-negative.
#### step size is given in 3rd arguement, bydefault its 50

In [22]:
np.linspace(0,5)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [23]:
np.linspace(0,1,5) ### linspace - equally space b/w them. Here number start from 0 and end with 1 with equally space b/w them with 5 parts. 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [24]:
np.linspace(0,5,10) ### Shift + Tab => open Documentation Help Box

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

#### np.eye()
#### identity matrix
#### takes single argument are number of rows n colums n
#### np.eye(5) gives identity matrix of 5 rows n columns n
#### default data type is float

In [25]:
np.eye(5) ### Identity matrix with order 5x5. Here in the diagonal is float number(1.)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.eye(5,dtype=int) ### In the diagonal is integer number.

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

#### np.random.rand(2,4)
#### 2 rows and 4 coulmns
#### always gives random values ranging betweeen 0 to 1
#### uniform distribution
#### only positive values

In [27]:
np.random.rand(2,4) 

array([[0.20442029, 0.83012895, 0.01794241, 0.09924288],
       [0.98305285, 0.14097246, 0.2708485 , 0.2550432 ]])

In [28]:
np.random.rand(4) ### (4) - 1 rows and 4 columns .random numbers are betweem 0 and 1.

array([0.31644457, 0.54351108, 0.35573037, 0.60751041])

In [29]:
np.random.randn(4)  ### Here numbers are positive and negative.
                    ### random values ranging -1 to 1
                    ### standard normal distribution

array([ 0.2057361 ,  0.47967498, -0.70214348,  0.47236418])

In [30]:
np.random.randn(2,4) ### Here numbers are positive and negative.

array([[ 0.41849796,  0.09740822, -1.05569532, -0.29558881],
       [-1.63928079,  0.94957075, -0.47274944,  1.88072496]])

#### np.random.randint(0,10,15)
#### starts with 0
#### ends with 9
#### number of samples in 15
#### all random values and values are allowed to be repeated

In [31]:
np.random.randint(0,10,15) ### Here integer number is 15 from 0 to 9.

array([7, 4, 8, 9, 3, 7, 3, 3, 9, 7, 3, 4, 9, 8, 3])

In [32]:
np.random.randint(0,100,10)

array([46, 77, 78, 38, 56, 97, 96, 25, 22, 24])

In [33]:
np.random.randint(0,10,50)

array([1, 8, 8, 5, 4, 9, 9, 8, 5, 6, 9, 5, 3, 6, 0, 5, 4, 9, 1, 6, 9, 8,
       5, 7, 8, 4, 1, 4, 8, 7, 6, 2, 4, 9, 2, 2, 3, 6, 6, 1, 4, 1, 0, 3,
       4, 2, 2, 4, 6, 9])

In [34]:
np.random.randint(10) ## it always show only one value randomly

7

In [35]:
np.random.randint(0,10) ## it always show only one value randomly

7

In [36]:
arr = np.arange(0,20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [37]:
arr = np.arange(11,20)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [38]:
arr = np.arange(-10,20)
arr

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19])

In [39]:
rand_array = np.random.randint(0,10,20)
rand_array

array([8, 3, 9, 2, 8, 9, 8, 4, 5, 8, 3, 0, 6, 4, 6, 5, 7, 7, 6, 3])

In [40]:
rand_array.min() ### return minimum value in array

0

In [41]:
rand_array.argmin() ### arg - index ### Return index value of minimum value

11

In [42]:
rand_array.max()   ### return maximum value in array

9

In [43]:
rand_array.argmax() ### arg - index ### Return index value of maximum value

2

In [44]:
rand_array.dtype  ### Return Integer type

dtype('int32')

In [45]:
type(rand_array)

numpy.ndarray

In [46]:
identity_matrix = np.eye(2,dtype=int)
identity_matrix

array([[1, 0],
       [0, 1]])

In [47]:
rand_matrix = np.random.rand(3,4)
rand_matrix

array([[0.23941379, 0.25633223, 0.33206863, 0.33606485],
       [0.07475921, 0.01623231, 0.31926773, 0.55681435],
       [0.93602679, 0.77372696, 0.16903713, 0.90339787]])

In [48]:
rand_matrix.T  ### Transpose - change rows to columns and columns to rows.

array([[0.23941379, 0.07475921, 0.93602679],
       [0.25633223, 0.01623231, 0.77372696],
       [0.33206863, 0.31926773, 0.16903713],
       [0.33606485, 0.55681435, 0.90339787]])

In [49]:
sample_array = np.arange(50,70)
sample_array

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69])

In [50]:
sample_array = sample_array.reshape(5,4)  ### make new matrix of order 5x4 from 1-D array by using reshape().
sample_array

array([[50, 51, 52, 53],
       [54, 55, 56, 57],
       [58, 59, 60, 61],
       [62, 63, 64, 65],
       [66, 67, 68, 69]])

In [51]:
sample_array = sample_array.reshape(10,2)  ### make new matrix of order 10x2 from 1-D array by using reshape().
sample_array

array([[50, 51],
       [52, 53],
       [54, 55],
       [56, 57],
       [58, 59],
       [60, 61],
       [62, 63],
       [64, 65],
       [66, 67],
       [68, 69]])

In [52]:
sample_array = sample_array.reshape(8,2)  ### ValueError: cannot reshape array of size 20 into shape (8,2)
sample_array 

ValueError: cannot reshape array of size 20 into shape (8,2)

In [53]:
np.ones(3, dtype=int)

array([1, 1, 1])

In [54]:
arr = np.arange(1,10)
arr1 = arr.reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [56]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [57]:
sample_array[9] = 200 ### change all Elements of 9th Row with 200.
sample_array

array([[ 50,  51],
       [ 52,  53],
       [ 54,  55],
       [ 56,  57],
       [ 58,  59],
       [ 60,  61],
       [ 62,  63],
       [ 64,  65],
       [ 66,  67],
       [200, 200]])

In [58]:
array = np.arange(50,200)
array

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
       102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
       115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
       128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
       141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
       154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166,
       167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179,
       180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192,
       193, 194, 195, 196, 197, 198, 199])

In [59]:
array[1:12] ### start from index 1 to index 11. 12th index is not included.

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61])

In [60]:
array[3:9]

array([53, 54, 55, 56, 57, 58])

In [61]:
array[0:7]

array([50, 51, 52, 53, 54, 55, 56])

In [62]:
array[:]  ### display all elements of array 

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
       102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
       115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
       128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
       141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
       154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166,
       167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179,
       180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192,
       193, 194, 195, 196, 197, 198, 199])

In [63]:
array[-1] ### Last Element

199

In [64]:
array[-4:]  ## Last Four Element

array([196, 197, 198, 199])

In [65]:
array[:-4]  ## All Elements Except last 4 Elements

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
       102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
       115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
       128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
       141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
       154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166,
       167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179,
       180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192,
       193, 194, 195])

In [66]:
subset_array = array[0:7]
subset_array

array([50, 51, 52, 53, 54, 55, 56])

In [67]:
array[:] = 1001 ### replaced all elements of array with 1001
array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001])

# Two-Dimensional Array

In [68]:
import numpy as sad ### "sad" do work same as "np"

In [69]:
sample_list = [[15,20,12,15],[80,15,20,40],[60,45,15,20]]
sample_matrix = sad.array(sample_list)  ### 2-D Array

In [70]:
sample_matrix

array([[15, 20, 12, 15],
       [80, 15, 20, 40],
       [60, 45, 15, 20]])

In [71]:
sample_matrix[2][2] 

15

In [72]:
sample_matrix[2][1]

45

In [73]:
sample_matrix[2,2] 

15

In [74]:
sample_matrix[1][2] 

20

In [75]:
sample_matrix[:,2] ### : - All rows and 2nd column

array([12, 20, 15])

In [76]:
sample_matrix[1,1]

15

In [77]:
sample_matrix[1:3,2:4]

array([[20, 40],
       [15, 20]])

In [78]:
sample_matrix[1:,2:]

array([[20, 40],
       [15, 20]])

In [79]:
sample_matrix[2] ### It's considering 2nd row.

array([60, 45, 15, 20])

###### --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [80]:
import numpy as np
matrix = np.array([[31,29,44],[62,19,65]])
matrix

array([[31, 29, 44],
       [62, 19, 65]])

In [81]:
matrix[0:1,1:2]

array([[29]])

In [82]:
matrix[0][1]

29

In [83]:
### Step 1: Create aarray this matrix ([[2, 6, 8],
###                                     [1, 5, 4],
###                                     [4, 3, 2]])
import numpy as np
list_of_list =[[2,6,8],[1,5,4],[4,3,2]]
array = np.array(list_of_list)
array

array([[2, 6, 8],
       [1, 5, 4],
       [4, 3, 2]])

In [84]:
### step 2: o/p [6,5,3]
array[:,1:2]

array([[6],
       [5],
       [3]])

In [85]:
### step 2: o/p [5,4]
array[1:2,1:3]

array([[5, 4]])

In [86]:
sample_matrix = np.array(([24,13,2,15],[15,2,54,65],[56,76,24,7]))
sample_matrix

array([[24, 13,  2, 15],
       [15,  2, 54, 65],
       [56, 76, 24,  7]])

In [87]:
sample_matrix[2][2]

24

In [88]:
sample_matrix[1][2]

54

In [89]:
import numpy as np

In [90]:
sample_array=np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [91]:
sample_array + sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [92]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [93]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [94]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [95]:
np.max(sample_array)

30

In [96]:
np.min(sample_array)

1

In [97]:
np.argmax(sample_array)

29

In [98]:
np.argmin(sample_array)

0

In [99]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [100]:
np.std(sample_array)

8.65544144839919

In [101]:
np.var(sample_array)

74.91666666666667

In [102]:
np.mean(sample_array)

15.5

In [103]:
array = np.random.randn(3,4) ### Random normal distribution
array

array([[ 0.11917089,  1.47966274, -1.02160547,  0.62469525],
       [ 0.57599794, -1.18295313, -2.248615  ,  0.68403684],
       [-0.21617584, -1.20510751, -0.32642313, -2.02592246]])

In [104]:
np.round(array,decimals=3)

array([[ 0.119,  1.48 , -1.022,  0.625],
       [ 0.576, -1.183, -2.249,  0.684],
       [-0.216, -1.205, -0.326, -2.026]])

In [105]:
sports=np.array(['golf','cricket','fball','cricket','basketball'])
np.unique(sports)

array(['basketball', 'cricket', 'fball', 'golf'], dtype='<U10')